// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title ArcanaVerifierStub
 * @notice Placeholder verifier for testing. MUST be replaced by the
 *         EZKL-generated ArcanaVerifier.sol before mainnet deployment.
 *
 * In production, the real verifier is generated by:
 *   python3 zkml/ezkl_setup.py
 * and automatically deployed via the deploy script.
 *
 * For hackathon demo purposes: this stub accepts any proof where
 * instances[0] matches a known test value, so the full UI flow
 * can be demonstrated without waiting for EZKL circuit compilation.
 */
contract ArcanaVerifierStub {
    address public owner;
    mapping(bytes32 => bool) public validProofHashes;

    event ProofRegistered(bytes32 proofHash, uint256 scoreInstance);

    constructor() {
        owner = msg.sender;
    }

    /**
     * @notice Verifies a ZK proof. In stub mode, accepts proofs registered by owner.
     *         Real EZKL verifier replaces this with on-chain Halo2 KZG verification.
     */
    function verifyProof(
        bytes calldata proof,
        uint256[] calldata instances
    ) external view returns (bool) {
        bytes32 proofHash = keccak256(abi.encodePacked(proof, instances));
        return validProofHashes[proofHash];
    }

    /**
     * @notice Register a valid proof hash (demo/testing only).
     */
    function registerProof(bytes calldata proof, uint256[] calldata instances) external {
        require(msg.sender == owner, "Only owner");
        bytes32 proofHash = keccak256(abi.encodePacked(proof, instances));
        validProofHashes[proofHash] = true;
        emit ProofRegistered(proofHash, instances.length > 0 ? instances[0] : 0);
    }

    /**
     * @notice Quick proof registration using just a hash string (for frontend testing).
     */
    function registerProofByHash(bytes32 proofHash) external {
        require(msg.sender == owner, "Only owner");
        validProofHashes[proofHash] = true;
    }
}
